"""Create device_types table

Revision ID: 4e3538a78e5b
Revises: a76f735be14c
Create Date: 2025-04-10 19:50:15.826674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3538a78e5b'
down_revision: Union[str, None] = 'a76f735be14c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('device_type_id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор типа устройства (Автоинкремент)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название типа устройства'),
    sa.PrimaryKeyConstraint('device_type_id', name=op.f('pk_device_types')),
    sa.UniqueConstraint('name', name='uq_device_types_name')
    )
    op.create_index(op.f('ix_device_types_name'), 'device_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_types_name'), table_name='device_types')
    op.drop_table('device_types')
    # ### end Alembic commands ###
