"""Create files table

Revision ID: 67f3b10a1b57
Revises: a921dc330717
Create Date: 2025-04-10 20:18:45.439690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f3b10a1b57'
down_revision: Union[str, None] = 'a921dc330717'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_devices_inventory_number', table_name='devices')
    op.create_index(op.f('ix_devices_inventory_number'), 'devices', ['inventory_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_inventory_number'), table_name='devices')
    op.create_index('ix_devices_inventory_number', 'devices', ['inventory_number'], unique=False)
    # ### end Alembic commands ###
