"""Create priorities table

Revision ID: 6885e529a5e0
Revises: 4e3538a78e5b
Create Date: 2025-04-10 19:58:25.155344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6885e529a5e0'
down_revision: Union[str, None] = '4e3538a78e5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('priorities',
    sa.Column('priority_id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор приоритета (Автоинкремент)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название приоритета'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Порядок отображения приоритетов (необязательно)'),
    sa.PrimaryKeyConstraint('priority_id', name=op.f('pk_priorities')),
    sa.UniqueConstraint('name', name='uq_priorities_name')
    )
    op.create_index(op.f('ix_priorities_name'), 'priorities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_priorities_name'), table_name='priorities')
    op.drop_table('priorities')
    # ### end Alembic commands ###
