"""add_is_final_field_to_statuses

Revision ID: 767c5ce7f331
Revises: b4feec98d7d1
Create Date: 2025-04-13 16:50:52.808593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '767c5ce7f331'
down_revision: Union[str, None] = 'b4feec98d7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Сначала добавляем столбец, который разрешает NULL значения
    op.add_column('statuses', sa.Column('is_final', sa.Boolean(), nullable=True, comment='Флаг завершающего статуса (закрывает заявку)'))
    
    # 2. Обновляем существующие записи, устанавливая значение по умолчанию
    op.execute("UPDATE statuses SET is_final = false")
    
    # 3. Изменяем столбец, делая его NOT NULL
    op.alter_column('statuses', 'is_final', nullable=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statuses', 'is_final')
    # ### end Alembic commands ###
