"""Create users table (regenerated)

Revision ID: a76f735be14c
Revises: 
Create Date: 2025-03-30 21:51:33.242641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76f735be14c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор пользователя (Автоинкремент)'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='Уникальный логин пользователя'),
    sa.Column('password_hash', sa.String(), nullable=False, comment='Хэшированный пароль пользователя'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Полное имя пользователя'),
    sa.Column('phone_number', sa.String(length=50), nullable=True, comment='Номер телефона пользователя'),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Роль пользователя (admin, technician, user)'),
    sa.Column('department', sa.String(length=255), nullable=True, comment='Отдел пользователя'),
    sa.Column('avatar_url', sa.String(), nullable=True, comment='URL аватара пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время создания записи'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Время последнего обновления записи'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
