"""Create devices table

Revision ID: a921dc330717
Revises: e8b35bf01585
Create Date: 2025-04-10 20:13:04.130463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a921dc330717'
down_revision: Union[str, None] = 'e8b35bf01585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), autoincrement=False, nullable=False, comment='Уникальный идентификатор устройства (НЕ автоинкремент)'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название устройства'),
    sa.Column('device_type_id', sa.Integer(), nullable=True, comment='Внешний ключ на тип устройства (может быть NULL)'),
    sa.Column('inventory_number', sa.String(length=100), nullable=True, comment='Инвентарный номер устройства (уникальный, может быть NULL)'),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.device_type_id'], name=op.f('fk_devices_device_type_id_device_types')),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_devices')),
    sa.UniqueConstraint('inventory_number', name='uq_devices_inventory_number')
    )
    op.create_index('ix_devices_device_type_id', 'devices', ['device_type_id'], unique=False)
    op.create_index('ix_devices_inventory_number', 'devices', ['inventory_number'], unique=False)
    op.create_index(op.f('ix_devices_name'), 'devices', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_name'), table_name='devices')
    op.drop_index('ix_devices_inventory_number', table_name='devices')
    op.drop_index('ix_devices_device_type_id', table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
