"""add_email_field_to_users

Revision ID: b4feec98d7d1
Revises: 78b6e5beb0f8
Create Date: 2025-04-13 13:24:19.044264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4feec98d7d1'
down_revision: Union[str, None] = '78b6e5beb0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True, comment='Email пользователя (необязательное поле)'))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Имя пользователя (необязательное поле)',
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Фамилия пользователя (необязательное поле)',
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Фамилия пользователя (необязательное поле)',
               existing_nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Имя пользователя (необязательное поле)',
               existing_nullable=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
