"""Create statuses table

Revision ID: e8b35bf01585
Revises: 6885e529a5e0
Create Date: 2025-04-10 20:02:32.647080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8b35bf01585'
down_revision: Union[str, None] = '6885e529a5e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор статуса (Автоинкремент)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название статуса'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Порядок отображения статусов (необязательно)'),
    sa.PrimaryKeyConstraint('status_id', name=op.f('pk_statuses')),
    sa.UniqueConstraint('name', name='uq_statuses_name')
    )
    op.create_index(op.f('ix_statuses_name'), 'statuses', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statuses_name'), table_name='statuses')
    op.drop_table('statuses')
    # ### end Alembic commands ###
